language: cpp
sudo: false
env:
  global:
    - ARDUINO_IDE_VERSION="1.8.11"
    - DISPLAY=:1.0
    - TEENSYDUINO_VERSION=153
install:
  # Install Arduino
  - wget --quiet https://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
  - mkdir $HOME/arduino_ide
  - tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz -C $HOME/arduino_ide/ 
  # Install Teensyduino
  - curl -fsSL https://www.pjrc.com/teensy/td_$TEENSYDUINO_VERSION/TeensyduinoInstall.linux64 -o TeensyduinoInstall.linux64
  - chmod +x TeensyduinoInstall.linux64
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - ./TeensyduinoInstall.linux64 --dir=$HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION
  # Install libaries
  - $HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION/arduino --install-library "Bounce2"
before_script:
  # Replace standard teensy headers with our custom ones
  - cp -rf ControlPanel/Build/Arduino/* $HOME/arduino_ide/*
script:
  - $HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION/arduino --verbose --board "teensy:avr:teensy40:usb=kbrawhid,speed=600,opt=o2std,keys=en-us" --verify ControlPanel/ControlPanel.ino

# Example build targets
#arduino --verbose --board "teensy:avr:teensy40:usb=kbrawhid,speed=600,opt=o2std,keys=en-us" --verify ControlPanel.ino
#arduino --board SparkFun:avr:promicro:cpu=8MHzatmega32U4 --verbose --verify LCDemoMatrix.ino